export const WorkoutArray = [
  { muscle: 'Upper Body', day: 0 },
  { muscle: 'Lower Body', day: 1 },
  { muscle: 'Upper Body', day: 2 },
  { muscle: 'Rest', day: 3 },
  { muscle: 'Upper Body', day: 4 },
  { muscle: 'Lower Body', day: 5 },
  { muscle: 'Upper Body', day: 6 },
  { muscle: 'Lower Body', day: 7 },
  { muscle: 'Upper Body', day: 8 },
  { muscle: 'Rest', day: 9 },
  { muscle: 'Upper Body', day: 10 },
  { muscle: 'Lower Body', day: 11 },
  { muscle: 'Upper Body', day: 12 },
  { muscle: 'Lower Body', day: 13 },
  { muscle: 'Upper Body', day: 14 },
  { muscle: 'Rest', day: 15 },
  { muscle: 'Upper Body', day: 16 },
  { muscle: 'Lower Body', day: 17 },
  { muscle: 'Upper Body', day: 18 },
  { muscle: 'Lower Body', day: 19 },
  { muscle: 'Upper Body', day: 20 },
  { muscle: 'Rest', day: 21 },
  { muscle: 'Upper Body', day: 22 },
  { muscle: 'Lower Body', day: 23 },
  { muscle: 'Upper Body', day: 24 },
  { muscle: 'Lower Body', day: 25 },
  { muscle: 'Upper Body', day: 26 },
  { muscle: 'Rest', day: 27 },
  { muscle: 'Upper Body', day: 28 },
  { muscle: 'Lower Body', day: 29 },
  { muscle: 'Upper Body', day: 30 },
  { muscle: 'Lower Body', day: 31 },
  { muscle: 'Upper Body', day: 32 },
  { muscle: 'Rest', day: 33 },
  { muscle: 'Upper Body', day: 34 },
  { muscle: 'Lower Body', day: 35 },
  { muscle: 'Upper Body', day: 36 },
  { muscle: 'Lower Body', day: 37 },
  { muscle: 'Upper Body', day: 38 },
  { muscle: 'Rest', day: 39 },
  { muscle: 'Upper Body', day: 40 },
  { muscle: 'Lower Body', day: 41 },
  { muscle: 'Upper Body', day: 42 },
  { muscle: 'Lower Body', day: 43 },
  { muscle: 'Upper Body', day: 44 },
  { muscle: 'Rest', day: 45 },
  { muscle: 'Upper Body', day: 46 },
  { muscle: 'Lower Body', day: 47 },
  { muscle: 'Upper Body', day: 48 },
  { muscle: 'Lower Body', day: 49 },
  { muscle: 'Upper Body', day: 50 },
  { muscle: 'Rest', day: 51 },
  { muscle: 'Upper Body', day: 52 },
  { muscle: 'Lower Body', day: 53 },
  { muscle: 'Upper Body', day: 54 },
  { muscle: 'Lower Body', day: 55 },
  { muscle: 'Upper Body', day: 56 },
  { muscle: 'Rest', day: 57 },
  { muscle: 'Upper Body', day: 58 },
  { muscle: 'Lower Body', day: 59 },
  { muscle: 'Upper Body', day: 60 },
  { muscle: 'Lower Body', day: 61 },
  { muscle: 'Upper Body', day: 62 },
  { muscle: 'Rest', day: 63 },
  { muscle: 'Upper Body', day: 64 },
  { muscle: 'Lower Body', day: 65 },
  { muscle: 'Upper Body', day: 66 },
  { muscle: 'Lower Body', day: 67 },
  { muscle: 'Upper Body', day: 68 },
  { muscle: 'Rest', day: 69 },
  { muscle: 'Upper Body', day: 70 },
  { muscle: 'Lower Body', day: 71 },
  { muscle: 'Upper Body', day: 72 },
  { muscle: 'Lower Body', day: 73 },
  { muscle: 'Upper Body', day: 74 },
  { muscle: 'Rest', day: 75 },
  { muscle: 'Upper Body', day: 76 },
  { muscle: 'Lower Body', day: 77 },
  { muscle: 'Upper Body', day: 78 },
  { muscle: 'Lower Body', day: 79 },
  { muscle: 'Upper Body', day: 80 },
  { muscle: 'Rest', day: 81 },
  { muscle: 'Upper Body', day: 82 },
  { muscle: 'Lower Body', day: 83 },
  { muscle: 'Upper Body', day: 84 },
  { muscle: 'Lower Body', day: 85 },
  { muscle: 'Upper Body', day: 86 },
  { muscle: 'Rest', day: 87 },
  { muscle: 'Upper Body', day: 88 },
  { muscle: 'Lower Body', day: 89 },
  { muscle: 'Upper Body', day: 90 },
  { muscle: 'Lower Body', day: 91 },
  { muscle: 'Upper Body', day: 92 },
  { muscle: 'Rest', day: 93 },
  { muscle: 'Upper Body', day: 94 },
  { muscle: 'Lower Body', day: 95 },
  { muscle: 'Upper Body', day: 96 },
  { muscle: 'Lower Body', day: 97 },
  { muscle: 'Upper Body', day: 98 },
  { muscle: 'Rest', day: 99 },
  { muscle: 'Upper Body', day: 100 },
  { muscle: 'Lower Body', day: 101 },
  { muscle: 'Upper Body', day: 102 },
  { muscle: 'Lower Body', day: 103 },
  { muscle: 'Upper Body', day: 104 },
  { muscle: 'Rest', day: 105 },
  { muscle: 'Upper Body', day: 106 },
  { muscle: 'Lower Body', day: 107 },
  { muscle: 'Upper Body', day: 108 },
  { muscle: 'Lower Body', day: 109 },
  { muscle: 'Upper Body', day: 110 },
  { muscle: 'Rest', day: 111 },
  { muscle: 'Upper Body', day: 112 },
  { muscle: 'Lower Body', day: 113 },
  { muscle: 'Upper Body', day: 114 },
  { muscle: 'Lower Body', day: 115 },
  { muscle: 'Upper Body', day: 116 },
  { muscle: 'Rest', day: 117 },
  { muscle: 'Upper Body', day: 118 },
  { muscle: 'Lower Body', day: 119 },
  { muscle: 'Upper Body', day: 120 },
  { muscle: 'Lower Body', day: 121 },
  { muscle: 'Upper Body', day: 122 },
  { muscle: 'Rest', day: 123 },
  { muscle: 'Upper Body', day: 124 },
  { muscle: 'Lower Body', day: 125 },
  { muscle: 'Upper Body', day: 126 },
  { muscle: 'Lower Body', day: 127 },
  { muscle: 'Upper Body', day: 128 },
  { muscle: 'Rest', day: 129 },
  { muscle: 'Upper Body', day: 130 },
  { muscle: 'Lower Body', day: 131 },
  { muscle: 'Upper Body', day: 132 },
  { muscle: 'Lower Body', day: 133 },
  { muscle: 'Upper Body', day: 134 },
  { muscle: 'Rest', day: 135 },
  { muscle: 'Upper Body', day: 136 },
  { muscle: 'Lower Body', day: 137 },
  { muscle: 'Upper Body', day: 138 },
  { muscle: 'Lower Body', day: 139 },
  { muscle: 'Upper Body', day: 140 },
  { muscle: 'Rest', day: 141 },
  { muscle: 'Upper Body', day: 142 },
  { muscle: 'Lower Body', day: 143 },
  { muscle: 'Upper Body', day: 144 },
  { muscle: 'Lower Body', day: 145 },
  { muscle: 'Upper Body', day: 146 },
  { muscle: 'Rest', day: 147 },
  { muscle: 'Upper Body', day: 148 },
  { muscle: 'Lower Body', day: 149 },
  { muscle: 'Upper Body', day: 150 },
  { muscle: 'Lower Body', day: 151 },
  { muscle: 'Upper Body', day: 152 },
  { muscle: 'Rest', day: 153 },
  { muscle: 'Upper Body', day: 154 },
  { muscle: 'Lower Body', day: 155 },
  { muscle: 'Upper Body', day: 156 },
  { muscle: 'Lower Body', day: 157 },
  { muscle: 'Upper Body', day: 158 },
  { muscle: 'Rest', day: 159 },
  { muscle: 'Upper Body', day: 160 },
  { muscle: 'Lower Body', day: 161 },
  { muscle: 'Upper Body', day: 162 },
  { muscle: 'Lower Body', day: 163 },
  { muscle: 'Upper Body', day: 164 },
  { muscle: 'Rest', day: 165 },
  { muscle: 'Upper Body', day: 166 },
  { muscle: 'Lower Body', day: 167 },
  { muscle: 'Upper Body', day: 168 },
  { muscle: 'Lower Body', day: 169 },
  { muscle: 'Upper Body', day: 170 },
  { muscle: 'Rest', day: 171 },
  { muscle: 'Upper Body', day: 172 },
  { muscle: 'Lower Body', day: 173 },
  { muscle: 'Upper Body', day: 174 },
  { muscle: 'Lower Body', day: 175 },
  { muscle: 'Upper Body', day: 176 },
  { muscle: 'Rest', day: 177 },
  { muscle: 'Upper Body', day: 178 },
  { muscle: 'Lower Body', day: 179 },
  { muscle: 'Upper Body', day: 180 },
  { muscle: 'Lower Body', day: 181 },
  { muscle: 'Upper Body', day: 182 },
  { muscle: 'Rest', day: 183 },
  { muscle: 'Upper Body', day: 184 },
  { muscle: 'Lower Body', day: 185 },
  { muscle: 'Upper Body', day: 186 },
  { muscle: 'Lower Body', day: 187 },
  { muscle: 'Upper Body', day: 188 },
  { muscle: 'Rest', day: 189 },
  { muscle: 'Upper Body', day: 190 },
  { muscle: 'Lower Body', day: 191 },
  { muscle: 'Upper Body', day: 192 },
  { muscle: 'Lower Body', day: 193 },
  { muscle: 'Upper Body', day: 194 },
  { muscle: 'Rest', day: 195 },
  { muscle: 'Upper Body', day: 196 },
  { muscle: 'Lower Body', day: 197 },
  { muscle: 'Upper Body', day: 198 },
  { muscle: 'Lower Body', day: 199 }
];